services:
  - type: redis
    plan: standard
    name: dev_redis
    region: frankfurt
    ipAllowList: [ ]

  - type: pserv
    name: dev_chroma
    runtime: image
    image:
      url: docker.io/chromadb/chroma:latest
    plan: standard
    envVars:
      - key: ANONYMIZED_TELEMETRY
        value: FALSE
      - key: IS_PERSISTENT
        value: TRUE
      - key: PERSIST_DIRECTORY
        value: /chromadb
      - fromGroup: veggie-scout-envs

    region: frankfurt
    disk:
      name: data
      mountPath: /chromadb
      sizeGB: 5

  - type: web
    name: dev_api
    runtime: docker
    repo: https://github.com/radu-mutilica/chat-with-repo
    plan: standard
    envVars:
      - key: SIM_SEARCH_TOP_K
        value: 30
      - key: LOG_LEVEL
        value: INFO
      - key: CHROMA_PASSWORD
        sync: false
      - key: CHROMA_USER
        sync: false
      - key: REDIS_URL
        fromService:
          name: dev_redis
          type: pserv
          property: connectionString
      - key: CHROMA_HOST
        fromService:
          name: dev_chroma
          type: pserv
          property: host
      - key: CHROMA_PORT
        fromService:
          name: dev_chroma
          type: pserv
          property: port
      - key: RERANKER_HOST
        fromService:
          name: dev_reranker
          type: pserv
          property: host
      - key: RERANKER_PORT
        fromService:
          name: dev_reranker
          type: pserv
          property: port
      - fromGroup: veggie-scout-envs
    region: frankfurt
    dockerCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    dockerContext: .
    dockerfilePath: ./api/Dockerfile
    buildFilter:
      ignoredPaths:
        - crawler/**
        - reranker/**
    rootDir: .

  - type: pserv
    name: dev_reranker
    runtime: docker
    repo: https://github.com/radu-mutilica/chat-with-repo
    plan: standard
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: CROSSENCODER_TOP_K
        value: 6
      - fromGroup: veggie-scout-envs
    region: frankfurt
    dockerCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    dockerContext: .
    dockerfilePath: ./reranker/Dockerfile
    buildFilter:
      ignoredPaths:
        - crawler/**
        - api/**
    rootDir: .

  - type: cron
    name: dev_crawler
    runtime: docker
    repo: https://github.com/radu-mutilica/chat-with-repo
    plan: standard
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: GITHUB_API_KEY
        sync: false
      - key: GITHUB_URL
        value: https://github.com/namoray/vision
      - key: CHROMA_NAME
        value: chromadb
      - key: CHROMA_HOST
        fromService:
          name: dev_chroma
          type: pserv
          property: host
      - key: CHROMA_PORT
        fromService:
          name: dev_chroma
          type: pserv
          property: port
      - key: MONGO_HOST
        fromService:
          name: dev_mongodb
          type: pserv
          property: host
      - key: MONGO_PORT
        fromService:
          name: dev_mongodb
          type: pserv
          property: port
      - fromGroup: veggie-scout-envs

    region: frankfurt
    schedule: '*/60 * * * *'
    dockerCommand: python main.py
    dockerContext: .
    dockerfilePath: ./crawler/Dockerfile
    rootDir: .

    buildFilter:
      ignoredPaths:
        - api/**
        - reranker/**


  - type: pserv
    name: dev_mongodb
    plan: standard
    runtime: docker
    autoDeploy: false
    region: frankfurt
    disk:
      name: stats
      mountPath: /data/db
      sizeGB: 5

version: "1"